Repository kubernetes-sigs/cluster-api-operator, pull requests merged in 2022-02, with the labels that each got.

#26 :bug: Added file to download kustomize
  hack/ensure-kustomize.sh
Labels: size/M, lgtm, cncf-cla: yes, approved

#25 ✨ Add command field to container spec
  api/v1alpha1/provider_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/operator.cluster.x-k8s.io_bootstrapproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_controlplaneproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_coreproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_infrastructureproviders.yaml
  controllers/component_customizer.go
  controllers/component_customizer_test.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#29 ✨ Remove unnecessary pointers from API
  api/v1alpha1/provider_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/operator.cluster.x-k8s.io_bootstrapproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_controlplaneproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_coreproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_infrastructureproviders.yaml
  controllers/component_customizer.go
  controllers/component_customizer_test.go
  controllers/phases.go
  controllers/phases_test.go
  controllers/preflight_checks.go
  controllers/preflight_checks_test.go
Labels: lgtm, cncf-cla: yes, approved, size/L

#28 🌱 Add Fedosin to OWNERS
  OWNERS_ALIASES
Labels: lgtm, cncf-cla: yes, approved, size/XS

#30 🐛Make version field required on API scheme level
  api/v1alpha1/provider_types.go
  config/crd/bases/operator.cluster.x-k8s.io_bootstrapproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_controlplaneproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_coreproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_infrastructureproviders.yaml
Labels: lgtm, cncf-cla: yes, approved, size/S
