Repository kubernetes-sigs/cluster-api-operator, pull requests merged in 2023-09, with the labels that each got.

#240 :book: Fix typo in helm command README, add recommended timeout value
  docs/README.md
Labels: lgtm, cncf-cla: yes, approved, size/S

#241 🌱 Bump k8s.io/* and golang.org/x/oauth2 modules manually
  Makefile
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/M, lgtm, cncf-cla: yes, approved

#219 ✨ Add support for addon providers
  api/v1alpha2/addonprovider_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/operator.cluster.x-k8s.io_addonproviders.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_addonproviders.yaml
  config/crd/patches/webhook_in_addonproviders.yaml
  config/webhook/manifests.yaml
  docs/README.md
  hack/charts/cluster-api-operator/templates/addon-conditions.yaml
  hack/charts/cluster-api-operator/templates/addon.yaml
  hack/charts/cluster-api-operator/values.yaml
  internal/controller/genericprovider/addonprovider_wrapper.go
  internal/controller/genericprovider_controller.go
  internal/controller/phases.go
  internal/webhook/addonprovier_webhook.go
  test/e2e/helpers_test.go
  test/e2e/minimal_configuration_test.go
  test/e2e/resources/full-chart-install.yaml
  util/util.go
Labels: lgtm, cncf-cla: yes, approved, size/XXL

#246 🌱 Update helm chart index.yaml
  index.yaml
Labels: lgtm, cncf-cla: yes, approved, size/S

#256 :bug: Fix url fetch from gitlab repository
  internal/controller/phases.go
Labels: lgtm, ok-to-test, cncf-cla: yes, approved, size/XS

#262 🌱 Remove TestAPIs from internal/controller
  go.mod
  go.sum
  internal/controller/suite_test.go
  internal/envtest/environment.go
Labels: lgtm, cncf-cla: yes, approved, size/S
