Repository kubernetes-sigs/cluster-api-operator, pull requests merged in 2023-08, with the labels that each got.

#200 📖 update docs for v0.5.0 release
  docs/README.md
Labels: lgtm, cncf-cla: yes, approved, size/S

#201 🌱 add e2e tests for compressed manifests in air-gapped environments
  test/e2e/compressed_manifests_test.go
Labels: lgtm, cncf-cla: yes, approved, size/L

#202 🐛 Support installing providers with custom names in air-gapped environments
  internal/controller/manifests_downloader.go
  internal/controller/phases.go
  test/e2e/compressed_manifests_test.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#203 ✨Inject additional manifests on provider installation/upgrade
  Tiltfile
  api/v1alpha1/provider_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/operator.cluster.x-k8s.io_bootstrapproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_controlplaneproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_coreproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_infrastructureproviders.yaml
  docs/README.md
  internal/controller/manifests_downloader.go
  internal/controller/phases.go
  internal/controller/phases_test.go
  internal/webhook/provider_webhook.go
  internal/webhook/provider_webhook_test.go
  test/e2e/minimal_configuration_test.go
Labels: lgtm, cncf-cla: yes, approved, size/L

#199 ✨ Create deployment template for helm chart
  Makefile
  config/chart/kustomization.yaml
  config/chart/manager_auth_proxy_patch.yaml
  config/chart/manager_image_patch.yaml
  config/chart/manager_pull_policy.yaml
  config/chart/manager_webhook_patch.yaml
  hack/charts/cluster-api-operator/templates/_helpers.tpl
  hack/charts/cluster-api-operator/templates/deployment.yaml
  hack/charts/cluster-api-operator/values.yaml
Labels: lgtm, cncf-cla: yes, approved, size/L

#206 🌱 Add a preflight check to validate core provider name
  api/v1alpha1/conditions_consts.go
  internal/controller/preflight_checks.go
  internal/controller/preflight_checks_test.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#211 🐛 Fix incorrect fieldSpecs paths
  config/crd/kustomizeconfig.yaml
  test/e2e/resources/full-chart-install.yaml
Labels: lgtm, cncf-cla: yes, approved, size/S

#212 🐛 Add generate workflow for full-chart-install test case
  Makefile
  test/e2e/helm_test.go
  test/e2e/resources/full-chart-install.yaml
Labels: size/M, lgtm, cncf-cla: yes, approved

#215 🌱 Use helm chart for cert-manager installation in e2e tests
  test/e2e/config/operator-dev.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/helm_test.go
  test/framework/all_type_helpers.go
  test/framework/helmcommand_string.go
  test/go.mod
  test/go.sum
  test/tools.go
Labels: lgtm, cncf-cla: yes, approved, size/L

#214 📖Document setting up new release branch jobs in release.md
  docs/release.md
Labels: lgtm, cncf-cla: yes, approved, size/S

#216 🐛 Fix imagePullSecrets bug
  hack/charts/cluster-api-operator/templates/deployment.yaml
  hack/charts/cluster-api-operator/values.yaml
Labels: lgtm, cncf-cla: yes, approved, size/S

#218 🌱 Update index.yaml for v0.5.1
  index.yaml
Labels: lgtm, cncf-cla: yes, approved, size/S

#222 🌱 Add missing dependabot configs
  .github/dependabot.yml
Labels: size/M, lgtm, cncf-cla: yes, approved

#230 🌱 Add dependabot groups. Allow additional patch updates
  .github/dependabot.yml
Labels: size/M, lgtm, cncf-cla: yes, approved

#220 ⚠️ Use v1alpha2 manifests in the helm chart
  hack/charts/cluster-api-operator/templates/bootstrap-conditions.yaml
  hack/charts/cluster-api-operator/templates/bootstrap.yaml
  hack/charts/cluster-api-operator/templates/control-plane-conditions.yaml
  hack/charts/cluster-api-operator/templates/control-plane.yaml
  hack/charts/cluster-api-operator/templates/core.yaml
  hack/charts/cluster-api-operator/templates/infra-conditions.yaml
  hack/charts/cluster-api-operator/templates/infra.yaml
  hack/charts/cluster-api-operator/values.yaml
  test/e2e/helm_test.go
  test/e2e/resources/all-providers-custom-ns-versions.yaml
  test/e2e/resources/all-providers-custom-versions.yaml
  test/e2e/resources/all-providers-latest-versions.yaml
  test/e2e/resources/multiple-bootstrap-custom-ns-versions.yaml
  test/e2e/resources/multiple-control-plane-custom-ns-versions.yaml
  test/e2e/resources/multiple-infra-custom-ns-versions.yaml
  test/e2e/resources/only-bootstrap.yaml
  test/e2e/resources/only-control-plane.yaml
  test/e2e/resources/only-infra.yaml
Labels: lgtm, cncf-cla: yes, approved, size/L
