Repository kubernetes-sigs/cluster-api-operator, pull requests merged in 2023-05, with the labels that each got.

#105 🐛 fix: ensure that all required env variables are set before running tests
  Makefile
  scripts/ci-e2e.sh
  test/e2e/config/operator-dev.yaml
Labels: lgtm, cncf-cla: yes, approved, size/S

#103 ✨ port to kubebuilder v4
  Dockerfile
  Makefile
  PROJECT
  cmd/main.go
  config/crd/bases/operator.cluster.x-k8s.io_bootstrapproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_controlplaneproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_coreproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_infrastructureproviders.yaml
  config/webhook/manifests.yaml
  controllers/alias.go
  hack/boilerplate.go.txt
  hack/boilerplate/README.md
  internal/controller/client_proxy.go
  internal/controller/component_customizer.go
  internal/controller/component_customizer_test.go
  internal/controller/consts.go
  internal/controller/genericprovider/bootstrapprovider_wrapper.go
  internal/controller/genericprovider/controlplaneprovider_wrapper.go
  internal/controller/genericprovider/coreprovider_wrapper.go
  internal/controller/genericprovider/genericprovider_interfaces.go
  internal/controller/genericprovider/infrastructureprovider_wrapper.go
  internal/controller/genericprovider_controller.go
  internal/controller/genericprovider_controller_test.go
  internal/controller/phases.go
  internal/controller/phases_test.go
  internal/controller/preflight_checks.go
  internal/controller/preflight_checks_test.go
  internal/controller/suite_test.go
  util/util.go
Labels: lgtm, cncf-cla: yes, approved, size/L

#107 ✨ support provider downgrades
  internal/controller/genericprovider_controller_test.go
  internal/controller/phases.go
  internal/envtest/environment.go
Labels: lgtm, cncf-cla: yes, approved, size/L

#108 🐛 Avoid failures on unchanged provider version
  internal/controller/genericprovider_controller_test.go
  internal/controller/phases.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#111 ✨ support gitlab repos
  internal/controller/consts.go
  internal/controller/phases.go
  internal/controller/phases_test.go
Labels: lgtm, cncf-cla: yes, approved, size/L

#116 🌱 Bump kube-rbac-proxy
  config/chart/manager_auth_proxy_patch.yaml
  config/default/manager_auth_proxy_patch.yaml
Labels: size/M, lgtm, cncf-cla: yes, approved

#117 🌱 Bump CAPI, controller tools and other dependencies
  Makefile
  config/crd/bases/operator.cluster.x-k8s.io_bootstrapproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_controlplaneproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_coreproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_infrastructureproviders.yaml
  go.mod
  go.sum
  hack/cert-manager.sh
  hack/ensure-kind.sh
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/helpers.go
Labels: size/XL, lgtm, cncf-cla: yes, approved

#118 🌱 Configure importas linter and fix import issues
  .golangci.yaml
  controllers/alias.go
  internal/controller/component_customizer_test.go
  internal/webhook/bootstrapprovider_webhook.go
  internal/webhook/controlplaneprovider_webhook.go
  internal/webhook/coreprovider_webhook.go
  internal/webhook/infrastructureprovider_webhook.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#125 🌱 Bump golangci lint version to v1.52.2
  .github/workflows/golangci-lint.yml
  Makefile
Labels: lgtm, cncf-cla: yes, approved, size/XS

#115 🐛 Don't requeue provider if its spec is invalid
  internal/controller/preflight_checks.go
Labels: lgtm, cncf-cla: yes, approved, size/S

#121 🌱 add more e2e tests
  test/e2e/helpers.go
  test/e2e/minimal_configuration.go
Labels: lgtm, cncf-cla: yes, approved, size/L
