Repository kubernetes-sigs/cluster-api-operator, pull requests merged in 2023-10, with the labels that each got.

#263 🌱 Use apimachinery runtime to register API scheme
  api/v1alpha2/addonprovider_types.go
  api/v1alpha2/bootstrapprovider_types.go
  api/v1alpha2/controlplaneprovider_types.go
  api/v1alpha2/coreprovider_types.go
  api/v1alpha2/groupversion_info.go
  api/v1alpha2/infrastructureprovider_types.go
  api/v1alpha2/zz_generated.deepcopy.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#275 :sparkles: Allow running operator on ppc64le arch
  config/default/manager_auth_proxy_patch.yaml
  hack/charts/cluster-api-operator/values.yaml
  test/e2e/resources/full-chart-install.yaml
Labels: lgtm, cncf-cla: yes, approved, size/XS

#288 :bug: Fix leader elect helm chart args
  hack/charts/cluster-api-operator/templates/deployment.yaml
Labels: lgtm, ok-to-test, cncf-cla: yes, approved, size/XS
