Repository kubernetes-sigs/cluster-api-operator, pull requests merged in 2023-06, with the labels that each got.

#126 🌱 Add go.work/go.sum to .gitignore
  .gitignore
Labels: lgtm, cncf-cla: yes, approved, size/XS

#133 🐛 build: fix image push job by disabling CGO when building kustomize
  Makefile
Labels: lgtm, cncf-cla: yes, approved, size/XS

#131 🐛 Download and store manifests from provider URL
  internal/controller/genericprovider/bootstrapprovider_wrapper.go
  internal/controller/genericprovider/controlplaneprovider_wrapper.go
  internal/controller/genericprovider/coreprovider_wrapper.go
  internal/controller/genericprovider/genericprovider_interfaces.go
  internal/controller/genericprovider/infrastructureprovider_wrapper.go
  internal/controller/genericprovider_controller.go
  internal/controller/manifests_downloader.go
  internal/controller/manifests_downloader_test.go
  internal/controller/phases.go
  internal/controller/phases_test.go
  internal/envtest/environment.go
Labels: lgtm, cncf-cla: yes, approved, size/L

#139 📖 Fix typo in capi-operator-proposal.md
  docs/capi-operator-proposal.md
Labels: lgtm, ok-to-test, cncf-cla: yes, approved, size/XS

#135 ✨ Validate github token in preflight checks
  api/v1alpha1/conditions_consts.go
  config/chart/manager_auth_proxy_patch.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manager/manager.yaml
  docs/getting-started.md
  go.mod
  go.sum
  internal/controller/phases.go
  internal/controller/preflight_checks.go
  internal/controller/preflight_checks_test.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#136 🌱 Update OWNERS
  OWNERS
  OWNERS_ALIASES
Labels: lgtm, cncf-cla: yes, approved, size/XS

#137 🐛 Update linters and fix reported issues
  .golangci.yaml
  api/v1alpha1/provider_types.go
  cmd/main.go
  internal/controller/component_customizer.go
  internal/controller/component_customizer_test.go
  internal/controller/genericprovider/bootstrapprovider_wrapper.go
  internal/controller/genericprovider/controlplaneprovider_wrapper.go
  internal/controller/genericprovider/coreprovider_wrapper.go
  internal/controller/genericprovider/infrastructureprovider_wrapper.go
  internal/controller/genericprovider_controller.go
  internal/controller/genericprovider_controller_test.go
  internal/controller/phases.go
  internal/controller/preflight_checks_test.go
  internal/controller/suite_test.go
  internal/envtest/environment.go
  internal/webhook/bootstrapprovider_webhook.go
  internal/webhook/controlplaneprovider_webhook.go
  internal/webhook/coreprovider_webhook.go
  internal/webhook/infrastructureprovider_webhook.go
  webhook/alias.go
Labels: lgtm, cncf-cla: yes, approved, size/L

#145 🐛 prevent false lint error
  internal/controller/preflight_checks.go
Labels: lgtm, cncf-cla: yes, approved, size/XS

#146 🐛 add execution permission to ./scripts/ci-make.sh
  scripts/ci-make.sh
Labels: lgtm, cncf-cla: yes, approved, size/XS

#149 🐛 add execution permission to ./scripts/ci-make.sh
  scripts/ci-make.sh
Labels: lgtm, cncf-cla: yes, approved, size/XS

#143 🌱 Bump CAPI to v1.4.3 and minor fixes
  .gitignore
  Makefile
  go.mod
  go.sum
  internal/controller/manifests_downloader_test.go
  test/e2e/helpers.go
  test/e2e/minimal_configuration_test.go
Labels: lgtm, cncf-cla: yes, approved, size/S

#162 🐛 use correct conditions for reporting errors after preflight checks
  internal/controller/manifests_downloader.go
  internal/controller/phases.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#173 🐛 Always call customizeDeployment function
  internal/controller/component_customizer.go
Labels: lgtm, cncf-cla: yes, approved, size/XS

#154 📖 Add operator documentation
  README.md
  docs/README.md
  docs/capi-operator-proposal.md
  docs/getting-started.md
  docs/images/fig1.plantuml
  docs/images/fig1.png
  docs/images/fig2.plantuml
  docs/images/fig2.png
  docs/images/fig3.png
  docs/images/fig4.png
Labels: lgtm, cncf-cla: yes, approved, size/XXL

#175 :sparkles: Add support for ImagePullSecrets in DeploymentSpec
  .golangci.yaml
  api/v1alpha1/provider_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/operator.cluster.x-k8s.io_bootstrapproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_controlplaneproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_coreproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_infrastructureproviders.yaml
  internal/controller/component_customizer.go
  internal/controller/component_customizer_test.go
Labels: lgtm, ok-to-test, cncf-cla: yes, approved, size/L

#168 🐛 Update provider components if (and only if) its spec has been changed
  internal/controller/genericprovider_controller.go
  internal/controller/genericprovider_controller_test.go
  internal/controller/phases.go
Labels: lgtm, cncf-cla: yes, approved, size/L

#174 ✨ Add serviceAccountName to DeploymentSpec
  api/v1alpha1/provider_types.go
  config/crd/bases/operator.cluster.x-k8s.io_bootstrapproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_controlplaneproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_coreproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_infrastructureproviders.yaml
  internal/controller/component_customizer.go
  internal/controller/component_customizer_test.go
Labels: size/M, lgtm, ok-to-test, cncf-cla: yes, approved

#177 ✨ Add ability to specify a namespace for provider secret
  Makefile
  api/v1alpha1/provider_types.go
  config/chart/webhookcainjection_patch.yaml
  config/crd/bases/operator.cluster.x-k8s.io_bootstrapproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_controlplaneproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_coreproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_infrastructureproviders.yaml
  config/default/webhookcainjection_patch.yaml
  config/webhook/manifests.yaml
  internal/controller/phases.go
  internal/controller/phases_test.go
  internal/controller/preflight_checks.go
  internal/webhook/bootstrapprovider_webhook.go
  internal/webhook/controlplaneprovider_webhook.go
  internal/webhook/coreprovider_webhook.go
  internal/webhook/infrastructureprovider_webhook.go
  internal/webhook/provider_webhook.go
  internal/webhook/provider_webhook_test.go
Labels: lgtm, cncf-cla: yes, approved, size/L

#178 🌱 update docs for 0.4.0 release
  docs/README.md
  internal/controller/preflight_checks.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#181 🌱 Update helm chart index.yaml
  index.yaml
Labels: lgtm, cncf-cla: yes, approved, size/S
