Repository kubernetes-sigs/cluster-api-operator, pull requests merged in 2023-12, with the labels that each got.

#308 ✨Bump CAPI to v1.6.0-rc.1
  Makefile
  api/v1alpha2/addonprovider_types.go
  api/v1alpha2/bootstrapprovider_types.go
  api/v1alpha2/controlplaneprovider_types.go
  api/v1alpha2/coreprovider_types.go
  api/v1alpha2/groupversion_info.go
  api/v1alpha2/infrastructureprovider_types.go
  cmd/main.go
  config/manager/manager.yaml
  config/rbac/role.yaml
  docs/README.md
  go.mod
  go.sum
  hack/charts/cluster-api-operator/templates/deployment.yaml
  hack/charts/cluster-api-operator/values.yaml
  internal/controller/client_proxy.go
  internal/controller/manifests_downloader.go
  internal/controller/phases.go
  internal/controller/phases_test.go
  internal/controller/preflight_checks.go
  internal/envtest/environment.go
  test/e2e/resources/full-chart-install.yaml
  test/go.mod
  test/go.sum
Labels: lgtm, cncf-cla: yes, approved, size/XXL

#346 🐛 Fix version.sh script
  cmd/plugin/cmd/version.go
  hack/version.sh
  version/version.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#335 🌱 Disable dependabot for hack/* modules
  .github/dependabot.yml
Labels: size/M, lgtm, cncf-cla: yes, approved

#355 🌱 Remove downgrade e2e tests
  test/e2e/air_gapped_test.go
  test/e2e/minimal_configuration_test.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#352 🐛 Prevent propagation of OwnerReferences from provider manifests
  internal/controller/component_customizer.go
Labels: lgtm, cncf-cla: yes, approved, size/XS

#359 🐛 Delete all Cluster API CRDs before running air-gapped tests
  test/e2e/air_gapped_test.go
  test/e2e/e2e_suite_test.go
  test/go.mod
Labels: lgtm, cncf-cla: yes, approved, size/S

#358 ✨ Add artefacts collection after running e2e suite
  test/e2e/air_gapped_test.go
  test/e2e/compressed_manifests_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/helm_test.go
  test/e2e/helpers_test.go
  test/e2e/minimal_configuration_test.go
  test/e2e/resources/all-providers-custom-ns-versions.yaml
  test/e2e/resources/all-providers-custom-versions.yaml
  test/e2e/resources/core-cluster-api-v1.5.4.yaml
  test/e2e/resources/core-cluster-api-v1.6.0.yaml
  test/e2e/resources/multiple-bootstrap-custom-ns-versions.yaml
  test/e2e/resources/multiple-control-plane-custom-ns-versions.yaml
  test/e2e/resources/multiple-infra-custom-ns-versions.yaml
Labels: lgtm, cncf-cla: yes, approved, size/XXL

#353 🌱 Bump CAPI to v1.6.0
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: lgtm, cncf-cla: yes, approved, size/S
