Repository kubernetes-sigs/cluster-api-operator, pull requests merged in 2023-07, with the labels that each got.

#182 🌱 Enable nestif linter again
  .golangci.yaml
  internal/controller/component_customizer.go
  internal/controller/component_customizer_test.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#180 ✨Fetch latest provider version if it's not set in the spec
  Makefile
  api/v1alpha1/provider_types.go
  config/crd/bases/operator.cluster.x-k8s.io_bootstrapproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_controlplaneproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_coreproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_infrastructureproviders.yaml
  internal/controller/genericprovider_controller.go
  internal/controller/manifests_downloader.go
  internal/controller/phases.go
  internal/controller/phases_test.go
  internal/controller/preflight_checks.go
  internal/controller/preflight_checks_test.go
  test/e2e/air_gapped_test.go
  test/e2e/helpers_test.go
  test/e2e/minimal_configuration_test.go
  test/e2e/resources/core-cluster-api-v1.4.2.yaml
  test/e2e/resources/core-cluster-api-v1.4.3.yaml
Labels: lgtm, cncf-cla: yes, approved, size/XXL

#187 ✨Bump go version to v1.20.4
  .github/workflows/golangci-lint.yml
  .github/workflows/release.yaml
  .golangci.yaml
  Dockerfile
  Makefile
  cmd/main.go
  go.mod
  hack/chart-update/go.mod
  hack/ensure-go.sh
  hack/tools/go.mod
  scripts/ci-verify.sh
Labels: size/M, lgtm, cncf-cla: yes, approved

#193 🌱 compile capi operator binary only once in the Dockerfile
  Dockerfile
Labels: lgtm, cncf-cla: yes, approved, size/S

#186 🌱 Bump Cluster API to v1.5.0-rc.0
  .golangci.yaml
  config/crd/bases/operator.cluster.x-k8s.io_bootstrapproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_controlplaneproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_coreproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_infrastructureproviders.yaml
  go.mod
  go.sum
  hack/ensure-kind.sh
  hack/tools/go.mod
  hack/tools/go.sum
  internal/controller/client_proxy.go
  internal/controller/genericprovider_controller_test.go
  internal/controller/phases.go
  internal/webhook/bootstrapprovider_webhook.go
  internal/webhook/controlplaneprovider_webhook.go
  internal/webhook/coreprovider_webhook.go
  internal/webhook/infrastructureprovider_webhook.go
Labels: size/XL, lgtm, cncf-cla: yes, approved

#191 ✨ Create operator CRs based on helm values
  Makefile
  docs/README.md
  hack/charts/cluster-api-operator/.helmignore
  hack/charts/cluster-api-operator/Chart.yaml
  hack/charts/cluster-api-operator/templates/bootstrap-conditions.yaml
  hack/charts/cluster-api-operator/templates/bootstrap.yaml
  hack/charts/cluster-api-operator/templates/cert-manager.namespace.yaml
  hack/charts/cluster-api-operator/templates/control-plane-conditions.yaml
  hack/charts/cluster-api-operator/templates/control-plane.yaml
  hack/charts/cluster-api-operator/templates/core.yaml
  hack/charts/cluster-api-operator/templates/infra-conditions.yaml
  hack/charts/cluster-api-operator/templates/infra.yaml
  hack/charts/cluster-api-operator/values.yaml
  test/e2e/air_gapped_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/helm_test.go
  test/e2e/helpers_test.go
  test/e2e/resources/all-providers-custom-ns-versions.yaml
  test/e2e/resources/all-providers-custom-versions.yaml
  test/e2e/resources/all-providers-latest-versions.yaml
  test/e2e/resources/multiple-bootstrap-custom-ns-versions.yaml
  test/e2e/resources/multiple-control-plane-custom-ns-versions.yaml
  test/e2e/resources/multiple-infra-custom-ns-versions.yaml
  test/e2e/resources/only-bootstrap.yaml
  test/e2e/resources/only-control-plane.yaml
  test/e2e/resources/only-infra.yaml
Labels: lgtm, cncf-cla: yes, approved, size/XXL

#192 🐛 Compress components manifests if they don't fit in the configmap
  docs/README.md
  go.mod
  go.sum
  internal/controller/manifests_downloader.go
  internal/controller/phases.go
  internal/controller/phases_test.go
  test/e2e/compressed_manifests_test.go
Labels: lgtm, cncf-cla: yes, approved, size/L

#197 🌱 Bump CAPI to v1.5.0
  go.mod
  go.sum
Labels: size/M, lgtm, cncf-cla: yes, approved

#196 ✨ Initialize operator clusterctl plugin
  Makefile
  cmd/plugin/cmd/root.go
  cmd/plugin/cmd/upgrade.go
  cmd/plugin/main.go
  go.mod
Labels: lgtm, cncf-cla: yes, approved, size/L
