Repository kubernetes-sigs/cluster-api-operator, pull requests merged in 2023-11, with the labels that each got.

#297 📖 Add CAPI operator quickstart docs
  docs/quickstart.md
Labels: size/M, lgtm, cncf-cla: yes, approved

#280 ✨ Allow JSON merge patches for provider manifests
  api/v1alpha1/provider_conversion.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1alpha2/provider_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/operator.cluster.x-k8s.io_addonproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_bootstrapproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_controlplaneproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_coreproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_infrastructureproviders.yaml
  docs/README.md
  go.mod
  internal/controller/component_patches.go
  internal/controller/phases.go
  internal/patch/matchinfo.go
  internal/patch/mergepatch.go
  internal/patch/patch.go
  internal/patch/patch_test.go
  internal/patch/resource.go
  test/e2e/minimal_configuration_test.go
  test/e2e/resources/full-chart-install.yaml
Labels: size/XL, lgtm, cncf-cla: yes, approved

#250 ✨ Add provider healthcheck controller
  api/v1alpha2/conditions_consts.go
  cmd/main.go
  internal/controller/genericprovider_controller.go
  internal/controller/healthcheck/healthcheck_controller.go
  internal/controller/healthcheck/healthcheck_controller_test.go
  internal/controller/healthcheck/suite_test.go
Labels: lgtm, cncf-cla: yes, approved, size/L

#321 🐛 Use absolute path to refer to operator installation from quickstart
  docs/quickstart.md
Labels: lgtm, cncf-cla: yes, approved, size/XS

#323 ✨ Update helm chart repo index
  index.yaml
Labels: lgtm, cncf-cla: yes, approved, size/S

#322 🌱 Add furkatgofurov7 to cluster-api-operator-admins list
  OWNERS_ALIASES
Labels: lgtm, cncf-cla: yes, approved, size/XS

#289 ✨ Add plugin skeleton
  cmd/plugin/cmd/delete.go
  cmd/plugin/cmd/doc.go
  cmd/plugin/cmd/init.go
  cmd/plugin/cmd/move.go
  cmd/plugin/cmd/root.go
  cmd/plugin/cmd/upgrade.go
  cmd/plugin/cmd/upgrade_apply.go
  cmd/plugin/cmd/upgrade_plan.go
  cmd/plugin/cmd/utils.go
  cmd/plugin/cmd/version.go
  go.mod
  go.sum
Labels: size/XL, lgtm, cncf-cla: yes, approved

#331 ✨ Add workflow for a book publishing job
  .github/workflows/documentation.yaml
  docs/book/Makefile
  docs/book/book.toml
  docs/book/src/01_intro.md
  docs/book/src/SUMMARY.md
  scripts/ci-install-mdbook.sh
Labels: lgtm, cncf-cla: yes, approved, size/L

#327 ✨ Allow clusterctl plugn to be installed with krew
  .github/workflows/release.yaml
  .goreleaser.yaml
  .krew.yaml
  Makefile
  docs/release.md
  hack/update-plugin-yaml.sh
Labels: size/M, lgtm, cncf-cla: yes, approved

#333 :bug: Always add index.yaml to the book directory
  docs/book/Makefile
Labels: lgtm, cncf-cla: yes, approved, size/XS

#340 ⚠️ Remove kube-rbac-proxy and expose metrics on localhost:8080
  cmd/main.go
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/rbac/auth_proxy_client_clusterrole.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/kustomization.yaml
  hack/charts/cluster-api-operator/templates/deployment.yaml
  hack/charts/cluster-api-operator/values.yaml
  test/e2e/resources/full-chart-install.yaml
Labels: lgtm, cncf-cla: yes, approved, size/L
