Repository kubernetes-sigs/cluster-api-operator, pull requests merged in 2023-03, with the labels that each got.

#72 🌱 Enable additional linters
  .github/workflows/golangci-lint.yml
  .golangci.yaml
  controllers/alias.go
  internal/controllers/client_proxy.go
  internal/controllers/component_customizer.go
  internal/controllers/component_customizer_test.go
  internal/controllers/genericprovider_controller.go
  internal/controllers/genericprovider_controller_test.go
  internal/controllers/phases.go
  internal/controllers/phases_test.go
  internal/controllers/preflight_checks.go
  internal/envtest/environment.go
  internal/webhook/bootstrapprovider_webhook.go
  internal/webhook/controlplaneprovider_webhook.go
  internal/webhook/coreprovider_webhook.go
  internal/webhook/infrastructureprovider_webhook.go
  main.go
  util/util.go
Labels: lgtm, cncf-cla: yes, approved, size/L

#77 ✨ Make tools installation consistent with other CAPI projects
  Makefile
  config/crd/bases/operator.cluster.x-k8s.io_bootstrapproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_controlplaneproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_coreproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_infrastructureproviders.yaml
  hack/ensure-golangci-lint.sh
  hack/ensure-kustomize.sh
  scripts/ci-e2e.sh
  scripts/go_install.sh
Labels: size/XL, lgtm, cncf-cla: yes, approved

#81 :book: Replace apiversion from management to operator
  docs/capi-operator-proposal.md
  docs/getting-started.md
Labels: lgtm, ok-to-test, cncf-cla: yes, approved, size/S

#80 ✨ Add new e2e tests
  Makefile
  test/e2e/helpers.go
  test/e2e/minimal_configuration.go
Labels: lgtm, cncf-cla: yes, approved, size/L

#48 📖 Update capi-operator-proposal.md
  docs/capi-operator-proposal.md
Labels: lgtm, ok-to-test, cncf-cla: yes, approved, size/XS

#87 📖 Add doc describing release process
  Makefile
  docs/release.md
  hack/get-project-maintainers.sh
Labels: size/M, lgtm, cncf-cla: yes, approved

#90 🌱 Bump golangci-lint to v1.51.2
  .github/workflows/golangci-lint.yml
  Makefile
Labels: lgtm, cncf-cla: yes, approved, size/XS

#92 🐛 Make release tag argument configurable
  Makefile
Labels: lgtm, cncf-cla: yes, approved, size/XS

#89 🌱 Stop using github.com/pkg/errors
  go.mod
  internal/controllers/client_proxy.go
  internal/controllers/phases.go
  internal/controllers/preflight_checks.go
  internal/envtest/environment.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#94 📖 Add helm chart to getting started doc
  docs/getting-started.md
  docs/release.md
Labels: lgtm, cncf-cla: yes, approved, size/S
