Repository kubernetes-sigs/cluster-api-operator, pull requests merged in 2023-02, with the labels that each got.

#50 🌱 Add alexander-demicev to OWNERS
  OWNERS_ALIASES
Labels: lgtm, cncf-cla: yes, approved, size/XS

#45 🌱 Bump k8s libraries to v1.25
  .github/workflows/golangci-lint.yml
  Dockerfile
  Makefile
  controllers/suite_test.go
  go.mod
  go.sum
  hack/ensure-go.sh
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  internal/envtest/environment.go
  test/e2e/e2e_suite_test.go
  test/e2e/minimal_configuration.go
Labels: lgtm, cncf-cla: yes, approved, size/XXL

#51 ⚠️ Move controllers to internal package
  controllers/alias.go
  internal/controllers/client_proxy.go
  internal/controllers/component_customizer.go
  internal/controllers/component_customizer_test.go
  internal/controllers/consts.go
  internal/controllers/genericprovider/bootstrapprovider_wrapper.go
  internal/controllers/genericprovider/controlplaneprovider_wrapper.go
  internal/controllers/genericprovider/coreprovider_wrapper.go
  internal/controllers/genericprovider/genericprovider_interfaces.go
  internal/controllers/genericprovider/infrastructureprovider_wrapper.go
  internal/controllers/genericprovider_controller.go
  internal/controllers/genericprovider_controller_test.go
  internal/controllers/phases.go
  internal/controllers/phases_test.go
  internal/controllers/preflight_checks.go
  internal/controllers/preflight_checks_test.go
  internal/controllers/suite_test.go
  internal/webhook/bootstrapprovider_webhook.go
  internal/webhook/controlplaneprovider_webhook.go
  internal/webhook/coreprovider_webhook.go
  internal/webhook/infrastructureprovider_webhook.go
  main.go
  util/util.go
  webhook/alias.go
Labels: lgtm, cncf-cla: yes, approved, size/L

#49 🌱 Add dependabot config
  .github/dependabot.yml
Labels: size/M, lgtm, cncf-cla: yes, approved

#57 🌱 Make dependabot ignore CAPI test
  .github/dependabot.yml
Labels: lgtm, cncf-cla: yes, approved, size/XS

#59 🌱 Add a development note to readme
  README.md
Labels: lgtm, cncf-cla: yes, approved, size/XS

#60 🌱 Update references from k8s.gcr.io to registry.k8s.io
  Makefile
  internal/controllers/component_customizer_test.go
Labels: kind/cleanup, priority/important-soon, lgtm, cncf-cla: yes, approved, size/XS

#61 🌱 Make logging more consistent
  internal/controllers/genericprovider_controller.go
  internal/controllers/phases.go
  internal/controllers/preflight_checks.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#63 ✨Remove clusterctl crds installation
  internal/controllers/phases.go
Labels: lgtm, cncf-cla: yes, approved, size/S

#67 ✨Add release make tasks
  Makefile
  Tiltfile
  cloudbuild.yaml
  config/default/manager_image_patch.yaml
  scripts/ci-e2e.sh
Labels: size/M, lgtm, cncf-cla: yes, approved

#66 📖 Add getting started docs
  docs/getting-started.md
Labels: lgtm, cncf-cla: yes, approved, size/L

#68 🌱 Increase cloudbuild timeout
  cloudbuild.yaml
Labels: lgtm, cncf-cla: yes, approved, size/XS

#69 🌱 Add make task for publishing docker manifests
  Makefile
Labels: lgtm, cncf-cla: yes, approved, size/S

#70 🌱 Install kustomize when releasing manifests
  Makefile
Labels: lgtm, cncf-cla: yes, approved, size/XS

#47 🌱 Update OWNERS
  OWNERS
  OWNERS_ALIASES
Labels: lgtm, cncf-cla: yes, approved, size/XS
