Repository kubernetes-sigs/cluster-api-operator, pull requests merged in 2024-10, with the labels that each got.

#616 :bug: Allow to use image overrides from mounted custerctl-config.yaml file
  internal/controller/image_overrides.go
  internal/controller/image_overrides_test.go
  internal/controller/manifests_downloader_test.go
  internal/controller/phases.go
Labels: lgtm, cncf-cla: yes, approved, size/L

#571 :seedling: Add additional hook post-upgrade
  hack/charts/cluster-api-operator/templates/addon.yaml
  hack/charts/cluster-api-operator/templates/bootstrap.yaml
  hack/charts/cluster-api-operator/templates/control-plane.yaml
  hack/charts/cluster-api-operator/templates/core-conditions.yaml
  hack/charts/cluster-api-operator/templates/core.yaml
  hack/charts/cluster-api-operator/templates/infra-conditions.yaml
  hack/charts/cluster-api-operator/templates/infra.yaml
  test/e2e/resources/all-providers-custom-ns-versions.yaml
  test/e2e/resources/all-providers-custom-versions.yaml
  test/e2e/resources/all-providers-latest-versions.yaml
  test/e2e/resources/feature-gates.yaml
  test/e2e/resources/manager-defined-missing-other-infra-spec.yaml
  test/e2e/resources/multiple-bootstrap-custom-ns-versions.yaml
  test/e2e/resources/multiple-control-plane-custom-ns-versions.yaml
  test/e2e/resources/multiple-infra-custom-ns-versions.yaml
  test/e2e/resources/only-addon.yaml
  test/e2e/resources/only-bootstrap.yaml
  test/e2e/resources/only-control-plane.yaml
  test/e2e/resources/only-infra-and-addon.yaml
  test/e2e/resources/only-infra.yaml
Labels: lgtm, ok-to-test, cncf-cla: yes, approved, size/L

#620 🌱 Bump CAPI to v1.7.7 and other dependencies
  .github/workflows/golangci-lint.yml
  .github/workflows/pr-dependabot.yaml
  .github/workflows/release.yaml
  .golangci.yaml
  Makefile
  Tiltfile
  go.mod
  go.sum
  hack/chart-update/go.mod
  hack/ensure-go.sh
  hack/tools/go.mod
  hack/tools/go.sum
  netlify.toml
  test/go.mod
  test/go.sum
Labels: lgtm, cncf-cla: yes, approved, size/L

#621 🌱 Update helm chart index.yaml to v0.14.0
  index.yaml
  plugins/clusterctl-operator.yaml
Labels: size/M, lgtm, cncf-cla: yes, approved
