Repository kubernetes-sigs/cluster-api-operator, pull requests merged in 2024-12, with the labels that each got.

#536 :sparkles: Add featureGates to ControlPlaneProvider
  hack/charts/cluster-api-operator/templates/control-plane.yaml
  hack/charts/cluster-api-operator/templates/infra-conditions.yaml
  test/e2e/helm_test.go
  test/e2e/resources/kubeadm-manager-defined.yaml
Labels: lgtm, ok-to-test, cncf-cla: yes, approved, size/L

#649 🌱 Bump CAPI to 1.9
  Makefile
  cmd/main.go
  config/crd/bases/operator.cluster.x-k8s.io_addonproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_bootstrapproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_controlplaneproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_coreproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_infrastructureproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_ipamproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_runtimeextensionproviders.yaml
  go.mod
  go.sum
  internal/controller/genericprovider_controller.go
  internal/controller/healthcheck/healthcheck_controller.go
  test/e2e/resources/full-chart-install.yaml
  test/go.mod
  test/go.sum
Labels: lgtm, cncf-cla: yes, approved, size/XXL

#660 🌱 Bump golang.org/x/crypto to v0.31.0 in root and test go mod
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: size/M, lgtm, cncf-cla: yes, approved

#662 🌱 Update helm chart index.yaml to v0.15.0
  index.yaml
  plugins/clusterctl-operator.yaml
Labels: size/M, lgtm, cncf-cla: yes, approved

#663 🐛 Fix dependency version for make update-helm-plugin-repo
  hack/chart-update/go.mod
  hack/chart-update/go.sum
Labels: lgtm, cncf-cla: yes, approved, size/L

#665 🐛 Remove metricsBindAddr from helmchart
  hack/charts/cluster-api-operator/templates/deployment.yaml
  hack/charts/cluster-api-operator/values.yaml
  test/e2e/resources/full-chart-install.yaml
Labels: lgtm, ok-to-test, cncf-cla: yes, approved, size/S

#666 🌱 Implement healthz and readyz checks in the deployment
  hack/charts/cluster-api-operator/templates/deployment.yaml
  hack/charts/cluster-api-operator/values.yaml
  test/e2e/resources/full-chart-install.yaml
Labels: size/M, lgtm, cncf-cla: yes, approved

#668 :bug: Perform full chart install in e2e test
  test/e2e/helm_test.go
Labels: kind/bug, size/M, lgtm, cncf-cla: yes, approved, area/ci

#673 🌱 Update helm chart index.yaml to v0.15.1
  index.yaml
  plugins/clusterctl-operator.yaml
Labels: size/M, lgtm, cncf-cla: yes, approved
