Repository kubernetes-sigs/cluster-api-operator, pull requests merged in 2024-03, with the labels that each got.

#435 📖 Inital Netlify book structure version of operator
  docs/book/src/01_intro.md
  docs/book/src/CONTRIBUTING.MD
  docs/book/src/SUMMARY.md
  docs/book/src/code-of-conduct.md
  docs/book/src/developer/guide.md
  docs/book/src/developer/release.md
  docs/book/src/developer/v1alpha1-to-v1alpha2.md
  docs/book/src/installation/helm-chart-installation.md
  docs/book/src/installation/installation.md
  docs/book/src/installation/manifest-installation.md
  docs/book/src/installation/plugin-installation.md
  docs/book/src/introduction.md
  docs/book/src/reference/api_reference.md
  docs/book/src/reference/ci-jobs.md
  docs/book/src/reference/glossary.md
  docs/book/src/reference/providers.md
  docs/book/src/reference/reference.md
  docs/book/src/topics/air-gapped-environtment.md
  docs/book/src/topics/basic-capi-provider-installation.md
  docs/book/src/topics/capi-provides-lifecycle.md
  docs/book/src/topics/deleting-provider.md
  docs/book/src/topics/deleting-providers.md
  docs/book/src/topics/injecting-additional-manifests.md
  docs/book/src/topics/installing-capz.md
  docs/book/src/topics/installing-core-provider.md
  docs/book/src/topics/installing-provider.md
  docs/book/src/topics/modifying-provider.md
  docs/book/src/topics/topics.md
  docs/book/src/topics/upgrading-provider.md
  docs/book/src/user/concepts.md
  docs/book/src/user/quick-start.md
  docs/book/theme/css/general.css
  docs/book/theme/favicon.png
  docs/book/theme/highlight.css
Labels: lgtm, cncf-cla: yes, approved, size/XXL

#451 :bug: Collect correct manifest config map per provider while performing upgrade
  internal/controller/manifests_downloader.go
  internal/controller/manifests_downloader_test.go
  internal/controller/phases.go
  internal/controller/phases_test.go
  util/util.go
Labels: kind/bug, lgtm, cncf-cla: yes, approved, size/L

#453 don’t deliver cert-manager CRDs with cluster-api-operator chart
  Makefile
  hack/charts/cluster-api-operator/values.yaml
  hack/inject-cert-manager-chart-version.sh
Labels: lgtm, cncf-cla: yes, approved, size/S

#450 🌱 Autorun make generate tasks on each dependabot PR and commit the changes to a branch
  .github/workflows/pr-dependabot.yaml
  Makefile
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/operator.cluster.x-k8s.io_addonproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_bootstrapproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_controlplaneproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_coreproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_infrastructureproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_ipamproviders.yaml
  test/e2e/resources/full-chart-install.yaml
Labels: lgtm, cncf-cla: yes, approved, size/XXL

#460 🌱 Drop myself from owners
  OWNERS_ALIASES
Labels: lgtm, cncf-cla: yes, approved, size/XS

#467 🌱 Use 1.21 golang version for tools
  .github/workflows/pr-dependabot.yaml
Labels: lgtm, cncf-cla: yes, approved, size/XS

#462 📖 Add CAPI Operator book link to root README
  README.md
Labels: lgtm, cncf-cla: yes, approved, size/XS

#468 🌱 Ensure dependabot branch has a default tag for make generate
  Makefile
Labels: lgtm, cncf-cla: yes, approved, size/XS

#380 🌱 Bump go version to v1.21
  .github/workflows/golangci-lint.yml
  .github/workflows/release.yaml
  .golangci.yaml
  Makefile
  go.mod
  go.sum
  hack/chart-update/go.mod
  hack/chart-update/go.sum
  hack/ensure-go.sh
  test/go.mod
  test/go.sum
Labels: size/M, lgtm, cncf-cla: yes, approved

#474 🌱 Update helm chart index.yaml to v0.9.1
  index.yaml
  plugins/clusterctl-operator.yaml
Labels: size/M, lgtm, cncf-cla: yes, approved
