Repository kubernetes-sigs/cluster-api-operator, pull requests merged in 2024-01, with the labels that each got.

#370 ✨Add IPAM provider support
  PROJECT
  api/v1alpha2/ipamprovider_types.go
  api/v1alpha2/ipamprovider_wrapper.go
  api/v1alpha2/zz_generated.deepcopy.go
  cmd/main.go
  cmd/plugin/cmd/delete.go
  cmd/plugin/cmd/init.go
  cmd/plugin/cmd/upgrade_apply.go
  config/crd/bases/operator.cluster.x-k8s.io_ipamproviders.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_ipamproviders.yaml
  config/crd/patches/webhook_in_ipamproviders.yaml
  config/webhook/manifests.yaml
  docs/README.md
  internal/controller/healthcheck/healthcheck_controller.go
  internal/controller/phases.go
  internal/webhook/ipamprovider_webhook.go
  test/e2e/helpers_test.go
  test/e2e/minimal_configuration_test.go
  test/e2e/resources/full-chart-install.yaml
  util/util.go
Labels: lgtm, cncf-cla: yes, approved, size/XXL

#378 🌱 Bump cert-manager version to v1.13.2
  Makefile
  hack/cert-manager.sh
Labels: lgtm, cncf-cla: yes, approved, size/XS

#354 🌱 Refactor healthcheck to reconcile only owned deployments
  internal/controller/healthcheck/healthcheck_controller.go
Labels: lgtm, cncf-cla: yes, approved, size/L

#349 ✨Allow to utilize providers from clusterctl.yaml file in /config/clusterctl.yaml
  internal/controller/consts.go
  internal/controller/phases.go
  internal/controller/phases_test.go
  internal/controller/preflight_checks.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#386 🌱 Update helm chart index.yaml
  index.yaml
  plugins/clusterctl-operator.yaml
Labels: size/M, lgtm, cncf-cla: yes, approved

#379 🌱 Update owners
  OWNERS_ALIASES
Labels: lgtm, cncf-cla: yes, approved, size/XS

#390 🐛 Customize only provider deployments
  internal/controller/component_customizer.go
  internal/controller/component_customizer_test.go
Labels: lgtm, cncf-cla: yes, approved, size/S

#392 📖 Update release docs
  docs/release.md
Labels: lgtm, cncf-cla: yes, approved, size/S

#393 🌱 Update helm chart index.yaml
  index.yaml
  plugins/clusterctl-operator.yaml
Labels: size/M, lgtm, cncf-cla: yes, approved

#395 ⚠️ Add short names for custom resources
  api/v1alpha2/addonprovider_types.go
  api/v1alpha2/bootstrapprovider_types.go
  api/v1alpha2/controlplaneprovider_types.go
  api/v1alpha2/coreprovider_types.go
  api/v1alpha2/infrastructureprovider_types.go
  api/v1alpha2/ipamprovider_types.go
  config/crd/bases/operator.cluster.x-k8s.io_addonproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_bootstrapproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_controlplaneproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_coreproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_infrastructureproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_ipamproviders.yaml
  test/e2e/resources/full-chart-install.yaml
Labels: size/M, lgtm, cncf-cla: yes, approved

#397 🐛 don't customize non-manager deployments
  internal/controller/component_customizer.go
  internal/controller/component_customizer_test.go
Labels: lgtm, cncf-cla: yes, approved, size/L

#402 🌱 udpate goreleaser config to include ldflags
  .goreleaser.yaml
Labels: lgtm, ok-to-test, cncf-cla: yes, approved, size/S

#334 ✨ Implement Init plugin subcommand
  cmd/plugin/cmd/init.go
  cmd/plugin/cmd/init_test.go
  cmd/plugin/cmd/root.go
  cmd/plugin/cmd/suite_test.go
  cmd/plugin/cmd/utils.go
  go.mod
  internal/controller/consts.go
  internal/controller/manifests_downloader.go
  internal/controller/phases.go
  internal/controller/phases_test.go
  internal/envtest/environment.go
  test/testdata/cert-manager.crds.yaml
  util/util.go
Labels: lgtm, cncf-cla: yes, approved, size/XXL

#399 ✨ Execute provider upgrades when a version changes
  api/v1alpha2/conditions_consts.go
  internal/controller/client_proxy.go
  internal/controller/genericprovider_controller.go
  internal/controller/genericprovider_controller_test.go
  internal/controller/manifests_downloader.go
  internal/controller/phases.go
Labels: lgtm, cncf-cla: yes, approved, size/L

#400 ⚠️ Deprecate v1alpha1
  api/v1alpha1/bootstrapprovider_types.go
  api/v1alpha1/controlplaneprovider_types.go
  api/v1alpha1/coreprovider_types.go
  api/v1alpha1/infrastructureprovider_types.go
  config/crd/bases/operator.cluster.x-k8s.io_bootstrapproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_controlplaneproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_coreproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_infrastructureproviders.yaml
  test/e2e/resources/full-chart-install.yaml
Labels: size/M, lgtm, cncf-cla: yes, approved
