Repository kubernetes-sigs/cluster-api-operator, pull requests merged in 2024-05, with the labels that each got.

#517 🐛 fix go.mod for hack/tools
  hack/tools/go.mod
  hack/tools/go.sum
Labels: size/M, lgtm, cncf-cla: yes, approved

#408 ✨ Implement "upgrade plan" support
  cmd/plugin/cmd/init.go
  cmd/plugin/cmd/init_test.go
  cmd/plugin/cmd/upgrade.go
  cmd/plugin/cmd/upgrade_plan.go
  cmd/plugin/cmd/upgrade_plan_test.go
  cmd/plugin/cmd/utils.go
Labels: size/XL, lgtm, cncf-cla: yes, approved, area/plugin

#528 🌱 Bump cert-manager version to v1.14.5
  Makefile
  hack/cert-manager.sh
Labels: lgtm, cncf-cla: yes, approved, size/XS

#521 ⚠️ remove cert-manager support from helm chart
  Makefile
  docs/README.md
  docs/book/src/01_user/02_quick-start.md
  docs/book/src/02_installation/01_prerequisites.md
  docs/book/src/02_installation/02_manifest-installation.md
  docs/book/src/02_installation/02_plugin-installation.md
  docs/book/src/02_installation/03_manifest-installation.md
  docs/book/src/02_installation/04_helm-chart-installation.md
  docs/book/src/04_developer/02_guide.md
  hack/charts/cluster-api-operator/Chart.yaml
  hack/charts/cluster-api-operator/templates/cert-manager.namespace.yaml
  hack/charts/cluster-api-operator/values.yaml
  hack/inject-cert-manager-chart-version.sh
Labels: lgtm, cncf-cla: yes, approved, size/L

#533 🐛 Fix helm chart syntax errors
  hack/charts/cluster-api-operator/templates/core.yaml
  hack/charts/cluster-api-operator/templates/infra.yaml
Labels: lgtm, cncf-cla: yes, approved, size/XS
