Repository kubernetes-sigs/cluster-api-operator, pull requests merged in 2024-04, with the labels that each got.

#448 ✨ Ability to add provider specific featureGates with Helm
  hack/charts/cluster-api-operator/templates/core.yaml
  hack/charts/cluster-api-operator/templates/infra.yaml
  test/e2e/helm_test.go
  test/e2e/resources/feature-gates.yaml
Labels: lgtm, cncf-cla: yes, approved, size/L

#485 🌱 Update helm chart index.yaml to v0.9.2
  index.yaml
  plugins/clusterctl-operator.yaml
Labels: size/M, lgtm, cncf-cla: yes, approved

#486 🐛 Use absolute path in update scripts
  hack/update-helm-repo.sh
  hack/update-plugin-yaml.sh
Labels: lgtm, cncf-cla: yes, approved, size/S

#461 🐛 Plugin Init improvements
  cmd/plugin/cmd/init.go
  cmd/plugin/cmd/utils.go
Labels: lgtm, cncf-cla: yes, approved, size/L, area/plugin

#487 📖 Improvements to book
  docs/book/README.md
  docs/book/src/00_introduction.md
  docs/book/src/04_developer/00.md
  docs/book/src/04_developer/01_version_migration/00.md
  docs/book/src/04_developer/01_version_migration/01_v1alpha1-to-v1alpha2.md
Labels: size/M, lgtm, cncf-cla: yes, approved

#491 ✨ expose metrics port in operator deployment
  hack/charts/cluster-api-operator/templates/deployment.yaml
  test/e2e/resources/full-chart-install.yaml
Labels: lgtm, ok-to-test, cncf-cla: yes, approved, size/XS

#492 ✨ Add RuntimeExtension provider
  api/v1alpha2/runtimeextensionprovider_types.go
  api/v1alpha2/runtimeextensionprovider_wrapper.go
  api/v1alpha2/zz_generated.deepcopy.go
  cmd/main.go
  cmd/plugin/cmd/delete.go
  cmd/plugin/cmd/init.go
  cmd/plugin/cmd/init_test.go
  cmd/plugin/cmd/utils.go
  config/crd/bases/operator.cluster.x-k8s.io_runtimeextensionproviders.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_runtimeextensionproviders.yaml
  config/crd/patches/webhook_in_runtimeextensionproviders.yaml
  config/webhook/manifests.yaml
  internal/controller/healthcheck/healthcheck_controller.go
  internal/controller/phases.go
  internal/webhook/runtimeextensionprovider_webhook.go
  test/e2e/resources/full-chart-install.yaml
  util/util.go
Labels: lgtm, cncf-cla: yes, approved, size/XXL

#495 🌱 Bump golangci-lint to v1.57.2
  .github/workflows/golangci-lint.yml
  Makefile
  cmd/plugin/cmd/delete_test.go
  cmd/plugin/cmd/init_test.go
  cmd/plugin/cmd/utils.go
  internal/controller/client_proxy.go
  internal/controller/genericprovider_controller_test.go
  internal/controller/phases_test.go
  internal/patch/patch_test.go
  internal/webhook/provider_webhook_test.go
Labels: lgtm, cncf-cla: yes, approved, size/S

#493 🌱 Bump cluster-api to v1.7.0
  api/v1alpha1/provider_conversion.go
  cmd/main.go
  cmd/plugin/cmd/delete.go
  cmd/plugin/cmd/upgrade_plan.go
  config/crd/bases/operator.cluster.x-k8s.io_addonproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_bootstrapproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_controlplaneproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_coreproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_infrastructureproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_ipamproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_runtimeextensionproviders.yaml
  go.mod
  go.sum
  internal/controller/client_proxy.go
  internal/controller/component_customizer.go
  internal/controller/component_customizer_test.go
  internal/controller/genericprovider_controller_test.go
  internal/envtest/environment.go
  test/e2e/resources/full-chart-install.yaml
  test/go.mod
  test/go.sum
Labels: lgtm, cncf-cla: yes, approved, size/XXL

#494 🌱 Bump tooling
  Makefile
  api/v1alpha1/zz_generated.conversion.go
  hack/tools/go.mod
  hack/tools/go.sum
Labels: lgtm, cncf-cla: yes, approved, size/L

#501 ✨This PR updates index.yaml for v0.10.0. Automatically generated by ma…
  index.yaml
  plugins/clusterctl-operator.yaml
Labels: size/M, lgtm, cncf-cla: yes, approved

#500 Add helm.sh/resource-policy: keep to CRDs to prevent deletion
  config/chart/kustomization.yaml
  config/chart/patches/keep-crds.yaml
  test/e2e/resources/full-chart-install.yaml
Labels: lgtm, cncf-cla: yes, approved, size/S

#504 🌱 Update helm chart index.yaml to v0.10.1
  index.yaml
  plugins/clusterctl-operator.yaml
Labels: size/M, lgtm, cncf-cla: yes, approved

#505 🐛 Fix unsupportedProviderDowngradeMessage message
  internal/controller/preflight_checks.go
Labels: lgtm, cncf-cla: yes, approved, size/XS
