Repository kubernetes-sigs/cluster-api-operator, pull requests merged in 2024-02, with the labels that each got.

#407 ✨ Add a preflight check to prevent provider downgrades
  api/v1alpha2/conditions_consts.go
  internal/controller/preflight_checks.go
  internal/controller/preflight_checks_test.go
Labels: lgtm, cncf-cla: yes, approved, size/L

#419 🌱 update git state syntax to goreleaser 1.24
  .goreleaser.yaml
Labels: lgtm, ok-to-test, cncf-cla: yes, approved, size/XS

#403 🌱 Bump golangci-lint to v1.55.2
  .github/workflows/golangci-lint.yml
  Makefile
Labels: lgtm, cncf-cla: yes, approved, size/XS

#423 🌱 Temporarily disable IPAM provider e2e test
  test/e2e/minimal_configuration_test.go
Labels: lgtm, cncf-cla: yes, approved, size/XS

#409 ✨ Add to InfrastructureProvider spec.manager.featureGates
  hack/charts/cluster-api-operator/templates/infra.yaml
  hack/charts/cluster-api-operator/values.yaml
Labels: lgtm, ok-to-test, cncf-cla: yes, approved, size/S

#422 🐛 Restrict configmap lookup to the provider namespace
  internal/controller/manifests_downloader.go
  internal/controller/phases.go
  internal/controller/phases_test.go
  test/e2e/air_gapped_test.go
  test/e2e/helpers_test.go
  test/e2e/resources/core-cluster-api-v1.5.4.yaml
  test/e2e/resources/core-cluster-api-v1.6.0.yaml
Labels: size/M, lgtm, cncf-cla: yes, approved

#425 ✨ Add "env" section support to the helm chart
  hack/charts/cluster-api-operator/templates/deployment.yaml
  hack/charts/cluster-api-operator/values.yaml
Labels: lgtm, cncf-cla: yes, approved, size/XS

#429 🌱 Update kpromo version and set --use-ssh=false by default
  Makefile
Labels: lgtm, cncf-cla: yes, approved, size/XS

#430 🌱 Update helm chart index.yaml
  index.yaml
  plugins/clusterctl-operator.yaml
Labels: size/M, lgtm, cncf-cla: yes, approved
