Repository kubernetes-sigs/cluster-api-operator, pull requests merged in 2024-06, with the labels that each got.

#539 🌱 Add sync-wave annotations
  hack/charts/cluster-api-operator/templates/addon.yaml
  hack/charts/cluster-api-operator/templates/core.yaml
  hack/charts/cluster-api-operator/templates/infra-conditions.yaml
  hack/charts/cluster-api-operator/templates/infra.yaml
  test/e2e/resources/all-providers-custom-ns-versions.yaml
  test/e2e/resources/all-providers-custom-versions.yaml
  test/e2e/resources/all-providers-latest-versions.yaml
  test/e2e/resources/feature-gates.yaml
  test/e2e/resources/multiple-infra-custom-ns-versions.yaml
  test/e2e/resources/only-addon.yaml
  test/e2e/resources/only-infra-and-addon.yaml
  test/e2e/resources/only-infra.yaml
Labels: size/M, lgtm, cncf-cla: yes, approved

#551 ✨Update index.yaml for v0.11.0
  index.yaml
  plugins/clusterctl-operator.yaml
Labels: size/M, lgtm, cncf-cla: yes, approved

#550 📖 Correct Helm chart install instructions in docs + add warnings about --wait being required
  docs/README.md
  docs/book/src/01_user/02_quick-start.md
  docs/book/src/02_installation/04_helm-chart-installation.md
  docs/quickstart.md
Labels: size/M, lgtm, cncf-cla: yes, approved

#549 🌱 Add more cases to helm test
  test/e2e/helm_test.go
  test/e2e/resources/manager-defined-missing-other-infra-spec.yaml
Labels: lgtm, cncf-cla: yes, approved, size/L

#519 ⚠️ feat(rbac): use real ServiceAccount instead of default
  config/manager/manager.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  hack/charts/cluster-api-operator/templates/deployment.yaml
  test/e2e/resources/full-chart-install.yaml
Labels: lgtm, ok-to-test, cncf-cla: yes, approved, size/S
