Repository kubernetes-sigs/cluster-api-operator, pull requests merged in 2024-09, with the labels that each got.

#598 ✨ Pass image overrides to in-memory client
  internal/controller/manifests_downloader_test.go
  internal/controller/phases.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#599 ✨ Update index.yaml for v0.13.0 minor release
  index.yaml
  plugins/clusterctl-operator.yaml
Labels: size/M, lgtm, cncf-cla: yes, approved

#591 Remove the invalid caBundle, required for 1.31
  config/crd/patches/webhook_in_addonproviders.yaml
  config/crd/patches/webhook_in_bootstrapproviders.yaml
  config/crd/patches/webhook_in_controlplaneproviders.yaml
  config/crd/patches/webhook_in_coreproviders.yaml
  config/crd/patches/webhook_in_infrastructureproviders.yaml
  config/crd/patches/webhook_in_ipamproviders.yaml
  config/crd/patches/webhook_in_runtimeextensionproviders.yaml
  test/e2e/resources/full-chart-install.yaml
Labels: lgtm, cncf-cla: yes, approved, size/S

#565 :sparkles: Handle config secret updates
  cmd/main.go
  hack/charts/cluster-api-operator/templates/deployment.yaml
  hack/charts/cluster-api-operator/values.yaml
  internal/controller/genericprovider_controller.go
  internal/controller/genericprovider_controller_test.go
  internal/controller/manifests_downloader_test.go
  internal/controller/phases_test.go
  internal/controller/secrets_to_providers.go
  internal/controller/secrets_to_providers_test.go
  internal/controller/suite_test.go
  internal/webhook/provider_webhook_test.go
Labels: size/XL, lgtm, ok-to-test, cncf-cla: yes, approved

#601 🌱 Verify PR titles with shell script
  .github/workflows/verify.yml
  hack/verify-pr-title.sh
Labels: size/M, lgtm, cncf-cla: yes, approved

#603 🌱 Clarify release test infra steps
  docs/book/src/04_developer/01_release.md
  docs/book/src/05_reference/05_ci-jobs.md
  hack/verify-pr-title.sh
Labels: lgtm, cncf-cla: yes, approved, size/XS

#606 🌱 pr-verify: use env var for passing the PR title
  .github/workflows/verify.yml
Labels: lgtm, cncf-cla: yes, approved, size/XS
