Repository kubernetes-sigs/cluster-api-operator, pull requests merged in 2024-11, with the labels that each got.

#625 🐛 Fix remove namespace arg check for provider
  internal/controller/component_customizer.go
Labels: lgtm, ok-to-test, cncf-cla: yes, approved, size/XS

#632 🌱 Bump CAPI to v1.8.5
  Makefile
  api/v1alpha1/provider_conversion.go
  api/v1alpha1/provider_types.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/main.go
  cmd/plugin/cmd/init_test.go
  cmd/plugin/cmd/upgrade_plan_test.go
  config/crd/bases/operator.cluster.x-k8s.io_addonproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_bootstrapproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_controlplaneproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_coreproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_infrastructureproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_ipamproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_runtimeextensionproviders.yaml
  go.mod
  go.sum
  hack/cert-manager.sh
  hack/charts/cluster-api-operator/templates/deployment.yaml
  hack/tools/go.mod
  hack/tools/go.sum
  internal/controller/genericprovider_controller.go
  internal/controller/healthcheck/healthcheck_controller.go
  test/e2e/air_gapped_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/helm_test.go
  test/e2e/helpers_test.go
  test/e2e/minimal_configuration_test.go
  test/e2e/resources/all-providers-custom-ns-versions.yaml
  test/e2e/resources/all-providers-custom-versions.yaml
  test/e2e/resources/core-cluster-api-v1.5.4.yaml
  test/e2e/resources/core-cluster-api-v1.6.0.yaml
  test/e2e/resources/core-cluster-api-v1.7.7.yaml
  test/e2e/resources/core-cluster-api-v1.8.0.yaml
  test/e2e/resources/full-chart-install.yaml
  test/e2e/resources/multiple-bootstrap-custom-ns-versions.yaml
  test/e2e/resources/multiple-control-plane-custom-ns-versions.yaml
  test/e2e/resources/multiple-infra-custom-ns-versions.yaml
  test/go.mod
  test/go.sum
Labels: lgtm, cncf-cla: yes, approved, size/XXL

#622 📖 Improve release notes with additional information
  docs/book/src/04_developer/01_release.md
  hack/publish-index-changes.sh
Labels: size/M, lgtm, cncf-cla: yes, approved
