Repository kubernetes-sigs/cluster-api-operator, pull requests merged in 2024-07, with the labels that each got.

#561 📖 Fix manifestPatches field name
  docs/README.md
  docs/book/src/03_topics/02_configuration/04_patching-provider-manifests.md
Labels: lgtm, cncf-cla: yes, approved, size/S

#538 ✨ Add support for customizing additional provider deployments
  api/v1alpha1/provider_conversion.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1alpha2/provider_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/operator.cluster.x-k8s.io_addonproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_bootstrapproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_controlplaneproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_coreproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_infrastructureproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_ipamproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_runtimeextensionproviders.yaml
  hack/charts/cluster-api-operator/templates/infra.yaml
  internal/controller/component_customizer.go
  internal/controller/component_customizer_test.go
  test/e2e/resources/full-chart-install.yaml
Labels: lgtm, cncf-cla: yes, approved, size/XXL

#574 ✨ Update index.yaml for v0.12.0 minor release
  index.yaml
  plugins/clusterctl-operator.yaml
Labels: size/M, lgtm, cncf-cla: yes, approved
