Repository kubernetes-sigs/cluster-api-operator, pull requests merged in 2025-06, with the labels that each got.

#826 ✨ Expose internal controllers
  cmd/main.go
  controller/alias.go
  internal/controller/genericprovider_controller.go
  internal/controller/manifests_downloader.go
  internal/controller/manifests_downloader_test.go
  internal/controller/phases.go
  internal/controller/phases_test.go
  internal/controller/suite_test.go
Labels: lgtm, cncf-cla: yes, approved, size/L

#833 🌱 Remove deprecated cert-manager.enabled parameter references
  docs/quickstart.md
  test/e2e/helm_test.go
Labels: kind/cleanup, lgtm, cncf-cla: yes, approved, size/S

#838 🌱 Update helm chart index.yaml to v0.21.0
  index.yaml
  plugins/clusterctl-operator.yaml
Labels: size/M, lgtm, cncf-cla: yes, approved
