Repository kubernetes-sigs/cluster-api-operator, pull requests merged in 2025-04, with the labels that each got.

#764 :bug: Fix appliedSpecHashAnnotation set if PreflightCheckPassed is not True
  internal/controller/coreprovider_to_providers.go
  internal/controller/genericprovider_controller.go
  internal/controller/genericprovider_controller_test.go
  internal/controller/secrets_to_providers.go
Labels: kind/bug, lgtm, cncf-cla: yes, approved, size/L

#762 :seedling: Add more condition validations for providers in e2e tests
  api/v1alpha2/conditions_consts.go
  test/e2e/air_gapped_test.go
  test/e2e/compressed_manifests_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/helm_test.go
  test/e2e/helpers_test.go
  test/e2e/minimal_configuration_test.go
  test/framework/conditions.go
Labels: size/XL, lgtm, cncf-cla: yes, approved

#638 ⚠️ Make helm chart values extensible per component
  hack/charts/cluster-api-operator/templates/addon.yaml
  hack/charts/cluster-api-operator/templates/bootstrap.yaml
  hack/charts/cluster-api-operator/templates/control-plane.yaml
  hack/charts/cluster-api-operator/templates/core.yaml
  hack/charts/cluster-api-operator/templates/infra.yaml
  hack/charts/cluster-api-operator/templates/ipam.yaml
  hack/charts/cluster-api-operator/values.schema.json
  hack/charts/cluster-api-operator/values.yaml
  test/e2e/helm_test.go
  test/e2e/resources/multiple-infra-custom-ns-versions.yaml
Labels: size/XL, lgtm, ok-to-test, cncf-cla: yes, approved

#791 🌱 Update helm chart index.yaml to v0.19.0
  index.yaml
  plugins/clusterctl-operator.yaml
Labels: size/M, lgtm, cncf-cla: yes, approved

#789 ⚠️ Remove deprecated v1alpha1 API
  .golangci.yaml
  Makefile
  PROJECT
  api/v1alpha1/bootstrapprovider_types.go
  api/v1alpha1/conditions_consts.go
  api/v1alpha1/controlplaneprovider_types.go
  api/v1alpha1/coreprovider_types.go
  api/v1alpha1/doc.go
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/infrastructureprovider_types.go
  api/v1alpha1/provider_conversion.go
  api/v1alpha1/provider_conversion_test.go
  api/v1alpha1/provider_types.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1alpha2/provider_conversion.go
  cmd/main.go
  config/crd/bases/operator.cluster.x-k8s.io_bootstrapproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_controlplaneproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_coreproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_infrastructureproviders.yaml
  go.mod
  test/e2e/e2e_suite_test.go
  test/e2e/resources/full-chart-install.yaml
Labels: lgtm, cncf-cla: yes, approved, size/XXL

#794 :book: fix helm install instructions
  docs/README.md
  docs/book/src/01_user/02_quick-start.md
  docs/book/src/02_installation/04_helm-chart-installation.md
  docs/quickstart.md
Labels: lgtm, ok-to-test, cncf-cla: yes, approved, size/S
