Repository kubernetes-sigs/cluster-api-operator, pull requests merged in 2025-05, with the labels that each got.

#796 :bug: CAPI operator incorrectly finds the manager container if the number of containers is greater than one
  internal/controller/component_customizer.go
  internal/controller/component_customizer_test.go
Labels: size/M, lgtm, cncf-cla: yes, approved

#809 🌱 Fix spelling in controller metrics config description
  api/v1alpha2/controllermanagerconfig_types.go
  config/crd/bases/operator.cluster.x-k8s.io_addonproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_bootstrapproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_controlplaneproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_coreproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_infrastructureproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_ipamproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_runtimeextensionproviders.yaml
  test/e2e/resources/full-chart-install.yaml
Labels: size/M, lgtm, ok-to-test, cncf-cla: yes, approved

#810 ✨ Enable profiling for operator pod
  cmd/main.go
  config/manager/manager.yaml
  docs/book/src/04_developer/03_profiling.md
  hack/charts/cluster-api-operator/templates/deployment.yaml
  hack/charts/cluster-api-operator/values.yaml
  test/e2e/resources/full-chart-install.yaml
Labels: size/M, lgtm, cncf-cla: yes, approved

#812 🌱 Pass global concurrency number to manager
  cmd/main.go
  config/manager/manager.yaml
  hack/charts/cluster-api-operator/values.yaml
  internal/controller/phases.go
  internal/controller/phases_test.go
  test/e2e/resources/full-chart-install.yaml
Labels: size/M, lgtm, cncf-cla: yes, approved

#817 ✨ add fetchConfig support to IPAMProvider in chart
  hack/charts/cluster-api-operator/templates/ipam.yaml
Labels: lgtm, ok-to-test, cncf-cla: yes, approved, size/S

#814 🐛 Fix OCI source parsing issues
  internal/controller/oci_source.go
  internal/controller/oci_source_parse_test.go
Labels: lgtm, ok-to-test, cncf-cla: yes, approved, size/L

#816 🌱 Add examples for feature-gates in helm chart values.yaml
  hack/charts/cluster-api-operator/values.yaml
Labels: lgtm, ok-to-test, cncf-cla: yes, approved, size/XS
