Repository kubernetes-sigs/cluster-api-operator, pull requests merged in 2025-01, with the labels that each got.

#681 🐛 avoid empty manager field in ControlPlaneProvider when no features gates provided
  hack/charts/cluster-api-operator/templates/control-plane.yaml
Labels: lgtm, ok-to-test, cncf-cla: yes, approved, size/XS

#650 ✨ adding fetchConfig to InfrastructureProvider template in helmchart
  hack/charts/cluster-api-operator/templates/infra.yaml
  hack/charts/cluster-api-operator/values.yaml
Labels: lgtm, ok-to-test, cncf-cla: yes, approved, size/S

#683 ✨ Add OCI source for provider ConfigMap preparation
  api/v1alpha1/provider_conversion.go
  api/v1alpha1/provider_conversion_test.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1alpha2/provider_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  cmd/plugin/cmd/init.go
  cmd/plugin/cmd/init_test.go
  cmd/plugin/cmd/preload.go
  cmd/plugin/cmd/preload_test.go
  cmd/plugin/cmd/publish.go
  cmd/plugin/cmd/utils.go
  config/crd/bases/operator.cluster.x-k8s.io_addonproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_bootstrapproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_controlplaneproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_coreproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_infrastructureproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_ipamproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_runtimeextensionproviders.yaml
  go.mod
  go.sum
  internal/controller/manifests_downloader.go
  internal/controller/oci_source.go
  internal/controller/phases.go
  internal/controller/preflight_checks.go
  internal/controller/preflight_checks_test.go
  test/e2e/helpers_test.go
  test/e2e/minimal_configuration_test.go
  test/e2e/resources/full-chart-install.yaml
  test/e2e/resources/infrastructure-custom-v0.0.1-components.yaml
  test/e2e/resources/infrastructure-custom-v0.0.1-metadata.yaml
  test/e2e/resources/infrastructure-docker-v0.0.1-components.yaml
  test/e2e/resources/infrastructure-docker-v0.0.1-metadata.yaml
  test/e2e/resources/infrastructure-docker-v0.0.2-components.yaml
  test/e2e/resources/infrastructure-docker-v0.0.2-metadata.yaml
  test/go.mod
  test/go.sum
Labels: lgtm, cncf-cla: yes, approved, size/XXL

#687 :seedling: Make annotation and component constants public and exportable
  api/v1alpha2/provider_types.go
  internal/controller/manifests_downloader.go
  internal/controller/phases.go
Labels: size/M, lgtm, ok-to-test, cncf-cla: yes, approved

#690 📖 Document OCI source usage, publish and preload subcommands
  docs/book/src/02_installation/02_plugin-installation.md
  docs/book/src/03_topics/02_configuration/01_air-gapped-environtment.md
  docs/book/src/03_topics/03_plugin/00.md
  docs/book/src/03_topics/03_plugin/01_installation.md
  docs/book/src/03_topics/03_plugin/02_preload_subcommand.md
  docs/book/src/03_topics/03_plugin/03_publish_subcommand.md
Labels: lgtm, kind/documentation, cncf-cla: yes, approved, size/L

#694 🌱 Align kustomize layover structure with v5 version
  Makefile
  Tiltfile
  config/certmanager/certificate.yaml
  config/certmanager/kustomizeconfig.yaml
  config/chart/kustomization.yaml
  config/chart/kustomizeconfig.yaml
  config/chart/webhookcainjection_patch.yaml
  config/crd/kustomization.yaml
  config/crd/kustomizeconfig.yaml
  config/crd/patches/cainjection_in_addonproviders.yaml
  config/crd/patches/cainjection_in_bootstrapproviders.yaml
  config/crd/patches/cainjection_in_controlplaneproviders.yaml
  config/crd/patches/cainjection_in_coreproviders.yaml
  config/crd/patches/cainjection_in_infrastructureproviders.yaml
  config/crd/patches/cainjection_in_ipamproviders.yaml
  config/crd/patches/cainjection_in_runtimeextensionproviders.yaml
  config/default/kustomization.yaml
  config/default/kustomizeconfig.yaml
  config/default/manager_webhook_patch.yaml
  config/default/webhookcainjection_patch.yaml
  config/webhook/kustomizeconfig.yaml
  go.mod
  hack/chart-update/go.mod
  hack/tools/go.mod
  netlify.toml
  test/go.mod
Labels: lgtm, cncf-cla: yes, approved, size/L

#695 🌱 Bump Go version to 1.23.0
  .github/workflows/golangci-lint.yml
  .github/workflows/pr-dependabot.yaml
  .github/workflows/release.yaml
  .golangci.yaml
  Makefile
  Tiltfile
  cmd/plugin/cmd/upgrade_plan.go
  go.mod
  hack/chart-update/go.mod
  hack/ensure-go.sh
  hack/tools/go.mod
  internal/controller/component_customizer.go
  internal/controller/genericprovider_controller.go
  internal/controller/oci_source.go
  internal/controller/preflight_checks.go
  netlify.toml
  test/go.mod
Labels: size/M, lgtm, cncf-cla: yes, approved

#696 🌱 Use go version without the patch number in go.mod files
  go.mod
  hack/chart-update/go.mod
  hack/tools/go.mod
  test/go.mod
Labels: lgtm, cncf-cla: yes, approved, size/XS

#698 🐛 Downgrade kustomize version to v5.3.0
  Makefile
Labels: lgtm, cncf-cla: yes, approved, size/XS

#700 🐛 Bump gcb-docker-gcloud image tag in cloudbuild
  cloudbuild.yaml
Labels: lgtm, cncf-cla: yes, approved, size/XS

#697 :book: Simplifying ConfigMap with metadata configuration
  docs/book/src/03_topics/02_configuration/01_air-gapped-environtment.md
  docs/local-development.md
Labels: lgtm, ok-to-test, cncf-cla: yes, approved, size/S

#702 🌱 Update helm chart index.yaml to v0.16.0
  index.yaml
  plugins/clusterctl-operator.yaml
Labels: size/M, lgtm, cncf-cla: yes, approved
