Repository kubernetes-sigs/cluster-api-operator, pull requests merged in 2025-10, with the labels that each got.

#909 📖 add notes on building oci artifacts as well as using plain http
  docs/book/src/03_topics/02_configuration/01_air-gapped-environtment.md
Labels: lgtm, ok-to-test, cncf-cla: yes, approved, size/S

#910 🐛 Update existing conditions to have a non-empty Reason field
  internal/controller/genericprovider_controller.go
Labels: lgtm, ok-to-test, cncf-cla: yes, approved, size/S

#871 ✨ Implement diagnostics fields in Providers CRD
  api/v1alpha2/controllermanagerconfig_types.go
  config/crd/bases/operator.cluster.x-k8s.io_addonproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_bootstrapproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_controlplaneproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_coreproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_infrastructureproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_ipamproviders.yaml
  config/crd/bases/operator.cluster.x-k8s.io_runtimeextensionproviders.yaml
  internal/controller/component_customizer.go
  test/e2e/resources/full-chart-install.yaml
Labels: lgtm, ok-to-test, cncf-cla: yes, approved, size/L

#912 🌱 Update helm chart index.yaml to v0.24.0
  index.yaml
  plugins/clusterctl-operator.yaml
Labels: size/M, lgtm, cncf-cla: yes, approved
