Repository kubernetes-sigs/cluster-api-operator, pull requests merged in 2025-07, with the labels that each got.

#852 ✨ Expose clusterctl provider dependent logic for custom provider building
  api/v1alpha2/addonprovider_wrapper.go
  api/v1alpha2/bootstrapprovider_wrapper.go
  api/v1alpha2/controlplaneprovider_wrapper.go
  api/v1alpha2/coreprovider_wrapper.go
  api/v1alpha2/genericprovider_interfaces.go
  api/v1alpha2/infrastructureprovider_wrapper.go
  api/v1alpha2/ipamprovider_wrapper.go
  api/v1alpha2/runtimeextensionprovider_wrapper.go
  cmd/plugin/cmd/init_test.go
  cmd/plugin/cmd/preload.go
  cmd/plugin/cmd/upgrade_plan.go
  cmd/plugin/cmd/upgrade_plan_test.go
  controller/alias.go
  internal/controller/client_proxy.go
  internal/controller/genericprovider_controller.go
  internal/controller/manifests_downloader_test.go
  internal/controller/oci_source.go
  internal/controller/phases.go
  internal/controller/phases_test.go
  internal/controller/preflight_checks.go
  internal/controller/preflight_checks_test.go
  util/util.go
Labels: lgtm, cncf-cla: yes, approved, size/L

#857 🌱 Update helm chart index.yaml to v0.22.0
  index.yaml
  plugins/clusterctl-operator.yaml
Labels: size/M, lgtm, cncf-cla: yes, approved

#859 🐛 [OCI] Normalize provider type name when control plane
  api/v1alpha2/controlplaneprovider_wrapper.go
Labels: lgtm, cncf-cla: yes, approved, needs-ok-to-test, size/XS
